# -*- coding: utf-8 -*-
"""robottraining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1__bxsRZKudxnwrCocmv1kgyeJL2xJQl6
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/Seeed-Projects/lerobot.git
# %cd lerobot
!pip install -e ".[feetech]"

from huggingface_hub import login
login()

!hf auth whoami

from lerobot.datasets.lerobot_dataset import LeRobotDataset

dataset = LeRobotDataset("prishaakapasi/pick_place_v1")
print(dataset[0].keys())  # see what's in a sample

!pip install "transformers==4.46.3" "huggingface_hub==0.35.3"

!pip install "transformers==4.51.3" "huggingface_hub==0.35.3"

!pip install num2words

!lerobot-train \
    --dataset.repo_id=prishaakapasi/pick_place_v1 \
    --policy.type=smolvla \
    --policy.pretrained_path=lerobot/smolvla_base \
    --output_dir=outputs/train/pick_place_smolvla \
    --job_name=pick_place_smolvla \
    --policy.device=cuda \
    --wandb.enable=false \
    --policy.repo_id=prishaakapasi/pick_place_smolvla_policy

!lerobot-train \
    --dataset.repo_id=prishaakapasi/pick_place_v1 \
    --policy.type=smolvla \
    --policy.pretrained_path=lerobot/smolvla_base \
    --output_dir=outputs/train/pick_place_smolvla \
    --job_name=pick_place_smolvla \
    --policy.device=cuda \
    --wandb.enable=false \
    --policy.repo_id=prishaakapasi/pick_place_smolvla_policy \
    --steps=8000 \
    --save_freq=2000

!ls outputs/train/pick_place_smolvla

!lerobot-train \
    --dataset.repo_id=prishaakapasi/pick_place_v1 \
    --policy.type=smolvla \
    --policy.pretrained_path=lerobot/smolvla_base \
    --output_dir=outputs/train/pick_place_smolvla \
    --job_name=pick_place_smolvla \
    --policy.device=cuda \
    --wandb.enable=false \
    --policy.repo_id=prishaakapasi/pick_place_smolvla_policy \
    --steps=8000 \
    --save_freq=2000 \
    --resume=true

!find outputs/train/pick_place_smolvla -name "train_config.json"



!lerobot-train \
    --config_path=outputs/train/pick_place_smolvla/checkpoints/002000/pretrained_model/train_config.json \
    --resume=true